language: node_js
node_js:
- 8
addons:
  apt:
    packages:
    - bc
before_install:
- npm install -g npm
- npm install -g greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
script:
- gpg --keyserver ha.pool.sks-keyservers.net --recv-key 13F26F82E955B8B8CE469054F29CCEBC83FD4525
- mkdir -p ~/bin && curl -sSL -o ~/bin/jq $JQ_BINARY && chmod +x ~/bin/jq
- "./manage ci"
after_success: npm run test:codecov
env:
  global:
  - JQ_BINARY="https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64"
  - PATH="/usr/bin:$PATH"
  - secure: OpSQC4DJdx7RGW4mJFr6TdpG16HjETcER/cpZIrYcecBDF+dBr2ptBbwoMSz9yEAN5pOXG0ITiE4Vt54k88QUoMeQY8ZQC1ujMK9gAErkneTWZmMEHrlap4m4lFRWwy8nUqF9jTc7COLYkgwe63SBULkARohL8a6fQROMJrfWK8qwaum4+LT2nR1fmE62n89+so6di5fK+MNmf6XVqbqvRp76woSl/GsUyWaR2qIPCZPkb6jHoc1Y+GPZLlx5ZCY1HyzftfRIQQl5pnoriVXCLpugPeYJ9WHTPETynTDCkiX0iSvsoMPNm3MHEnaesWpl+XDjh69QkJjwPgXwWKT27NeBmmX1yMiwMuqpZ79N+0ZQfTsNxTm2MhfDYZP57jUGxbM2IdjPMKffB1GyHKfdSQGum4J6XW1gPWRZg7ycsI4Jd7RbSGsGELkPRRKoLfnlF/QOM5TI7N44F4KgYqG0sDlvsbJcxdQ86Z+QROKbXae0Fbz+ZQGi/Y4GZkQ1gPK+s/719P+Vq6uUiWKU1sBTlt95b1C/VCbfFxY7n2tl4jUe5XKIQemD7q78eNgs6hYlDb3jIZgK+sb/VyXHIEkBggwZmAcSeoZ6aT/uK0bnm4J0pYwEUw3lfmfS5PwN3xWlSB5y9b4nl+vkZV8qfqBDWMmCFCOu/Qg9Yb00mHQXqg=
  - secure: mC1oR7LaFb9T81rn2+k5C0qRlIzhKLveSQprsF94yqMC63Qqh2HVhtCaWaj6DxHxNbyuLBfRvFC2xIekG1dhtoJPdZgUEXSSmflItG+Oa3HlZtQZ7DOfNsxGClQ/SYKenLahyVRUnderckugzofAkKap0rr6Y5ZziB/TwEq3WucABKkqL2zMwQXLlcpCVoLrdc7842d899+y+yc3YO4g6IvIBmLxk8bX9IyUkwPDubGE5mzqUgKS0j5UboGyqrbKh5JsrBQ0VGS1+ecgkNEXZAETGexcPcGqr/Dx5rLLoRNBCXHytNpc2Tw4aG+3lbe7wnhp0JvwCnyyFGAwc158+5efE0JYNPKEz04Xbu76/SdFf0OSsvetbJrCXsuhBQ63Vo3TYoEkQEs9DN5m8FLfs/6o3WDwHxpo76Qw8ZGt8cyt6Dpm6Wc2JbPWUxNTQ2CHfc3rLWJmvLuRgRNIzepSu90go9y8/G+KMVCFZLrkykE2VNO4MKs9FYY5ET8hBMDog3le8Km8+SSJKriluUhUaeRsLyaahRY4dCVOliHcbjwfIFUUh5sO4UDfRkIdN3PCIuc3m14hBQLK59T8VxJy+scuZ5MuyXw9IpzCCVpehOo359QG7dY1GMica3c9GgF4+dVrEe4+T0lYUzDbfe/Tl+6bZKrHm+ITPrZTK2vX00U=
  - secure: Y6NMkq8deCwmMrXnGHvewyIEUXpZSDN55tbJxPMaQdw1/GVTzuK4wm12Yn2SsvFWxUTfpedW2b6pFm7aH4ZPUIBVq2ljQwTrwcSVeSbn2Vh06g55D6sVRRNY+1vxB3zGzRvL4qTsYUGeZfofUJfqZekBVR3/FK/COKIgcmXPm5FZpaKD7+9+zEdFhRdnOdc9dcZ9hz6oH+GCsZLqmogfSlbFUlQ7eeBkTvgnOfzPQaWMewjdE0wfJ0WALcqJV7Kw6s2oxra4lrCEA/Ei+0IqS9dz15ngNyOajcolygVJUlqhmxBf2sX6SMaOpeJvQfXjcoCQy092/fiUBDecFaUUwND6aTiF2b452yPFeIjRTyxv/rMxf93ZReMyMUpmva+shhxYDDyYS8RhwJrO7ieEYjBuzhzDUNQMNLnBZ93gan1idZz8IylrzI1VDHksWM6stMdHYUuVjewEhKoH2kVSL+/l+RZDAvO2x4qlyleq66ilL8aFR/y2BY2fvo+n/15t/pxCY+FVgfcXzmKE6qOAy8ucjVm2HZp7fhJFAWMbWapQeuX8GGtMr1dDU05G72Eh/COD3ibQai75XQTnmiOYFG3lGbNaDkL16xZN/OBYmGItpsTXwxbceNR66Dy0sG0+yAnk9CFiCLoBgml/0jOjB8t2We0rvi8+mGgnfPkCYhk=
